version: "3"
services:
  traefik:
    restart: unless-stopped
    image: traefik:latest
    command: --providers.docker=true
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fastapi-app-demo:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.fastapi-app-demo.rule=Host(`fastapi-app-demo.traefik.me`)"
      - "traefik.http.services.fastapi-app-demo.loadbalancer.server.port=8000"
    environment:
      PORT: 8000
