[tool.poetry]
name = "fastapi-app-demo"
version = "0.1.0"
description = ""
authors = ["Huynh Duc Dung <dunghd.it@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"
fastapi = "0.110.2"
uvicorn = "0.29.0"


[tool.poetry.group.test.dependencies]
httpx = "0.27.0"
pytest = "8.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
