[tool.poetry]
name = "fastapi-app-demo"
version = "0.1.0"
description = ""
authors = ["Huynh Duc Dung <dunghd.it@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.4"
fastapi = "0.112.0"
uvicorn = "0.30.5"


[tool.poetry.group.test.dependencies]
httpx = "0.27.0"
pytest = "8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
