name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
        poetry-version:
          - "1.7.1"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: "moonrepo/setup-toolchain@v0"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: moon run :install
      - name: Test
        run: moon run :test
