name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: "moonrepo/setup-toolchain@v0"
        with:
          auto-install: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: moon run :install
      - name: Test
        run: moon run :test
